project:
  type: book
  output-dir: docs

execute:
  warning: false
  message: false

book:
  title: "Handbook of Regression Modeling in People Analytics (2nd edition)"
  subtitle: "With Examples in R and Python"
  reader-mode: true

  page-footer:
    left: |
      Handbook of Regression Modeling in People Analytics (2nd ed.) was written by Keith McNulty.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: www/cover/coverpage.png
  favicon: www/cover/coverpage-og.png
  site-url: https://peopleanalytics-regression-book-2nd-edition.org/
  repo-url: https://github.com/keithmcnulty/regression-handbook-2nd-edition
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - foreword.qmd
    - introduction.qmd
    - importance.qmd
    - basic_r.qmd
    - primer_stats.qmd
    - linear_regression.qmd
    - binomial_logistic_regression.qmd
    - multinomial_regression.qmd
    - ordinal_regression.qmd
    - hierarchical_data.qmd
    - survival_analysis.qmd
    - power_tests.qmd
    - further.qmd
    - bibliography.qmd

format:
  html:
    theme:
      - materia
    code-link: false
    crossref:
      chapters: true

    author-meta: "Keith McNulty"
    callout-appearance: simple
    bibliography: book.bib

editor: source
